import ABBG2x from "./images/ABBG2x.jpg";

const cabels = [
  {
    name: 'Кабель алюминиевый',
    code: 2000,
    brand: 'АВВГ 2 х 2.5',
    possibleLoad: 3.2,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 2,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2007,
    brand: 'АВВГ 2 х 2.5',
    possibleLoad: 4,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 2.25,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2010,
    brand: 'АВВГ 2 х 2.5',
    possibleLoad: 5,
    insulationMaterial: '-',
    sheathMaterial: '-',
    outdoorUse: '-',
    indoorUse: '-',
    undergroundUse: '-',
    cost: 2.65,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2011,
    brand: 'АВВГ 2 х 2.5',
    possibleLoad: 4,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 2.65,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2020,
    brand: 'АВВГ 2 х 4',
    possibleLoad: 5.3,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 3.2,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2027,
    brand: 'АВВГ 2 х 4',
    possibleLoad: 6.2,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 3.4,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2031,
    brand: 'АВВГ 2 х 4',
    possibleLoad: 6.2,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 4.1,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2033,
    brand: 'АВВГ 2 х 4',
    possibleLoad: 6.2,
    insulationMaterial: 'кабельный пластикат',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 5.1,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2040,
    brand: 'АВВГ 2 х 6',
    possibleLoad: 7,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 4.2,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2047,
    brand: 'АВВГ 2 х 6',
    possibleLoad: 7,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 4.9,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2051,
    brand: 'АВВГ 2 х 6',
    possibleLoad: 8,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 5.8,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2053,
    brand: 'АВВГ 2 х 6',
    possibleLoad: 8,
    insulationMaterial: 'кабельный пластикат',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 6.55,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2060,
    brand: 'АВВГ 2 х 10',
    possibleLoad: 9.5,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 6.8,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2064,
    brand: 'АВВГ 2 х 10',
    possibleLoad: 11,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 8,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2066,
    brand: 'АВВГ 2 х 10',
    possibleLoad: 11,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 9,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2067,
    brand: 'АВВГ 2 х 10',
    possibleLoad: 11,
    insulationMaterial: 'кабельный пластикат',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 10.5,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2070,
    brand: 'АВВГ 2 х 16',
    possibleLoad: 14,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 11,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2074,
    brand: 'АВВГ 2 х 16',
    possibleLoad: 15.2,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный полиэтилен',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 12,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2076,
    brand: 'АВВГ 2 х 16',
    possibleLoad: 15.2,
    insulationMaterial: 'кабельный полиэтилен',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 14,
    img: ABBG2x
  },
  {
    name: 'Кабель алюминиевый',
    code: 2077,
    brand: 'АВВГ 2 х 16',
    possibleLoad: 15.2,
    insulationMaterial: 'кабельный пластикат',
    sheathMaterial: 'кабельный пластикат',
    outdoorUse: 'да',
    indoorUse: 'да',
    undergroundUse: 'да',
    cost: 14.6,
    img: ABBG2x
  },
]

export default cabels